install:
	pip install -r requirements.txt

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

runserver:
	python manage.py runserver

createsuperuser:
	python manage.py createsuperuser

test:
	python manage.py test

collectstatic:
	python manage.py collectstatic --noinput

showmigrations:
	python manage.py showmigrations
